server:
  jira: "https://my.jira.server.com"
  confluence: "https://my.confluence.server.com"

metrics:
  - status

fields:
  sprint: "customfield_10001"
  story_points: "customfield_10002"

report: &report
  space: "SPACE"
  parent_page: "My Parent Page"

workflow: &workflow
  - name: "Backlog"
    status:
      - "Backlog"
  - name: "In progress"
    status:
      - "In progress"
      - "In review"
  - name: "Done"
    status:
      - "Closed"

projects:
  - name: "Project name"
    jql: "project = TEST"
    report: *report
    workflow: *workflow
  - name: "Second project name"
    jql: "project = TEST2"
    report: *report
    workflow: *workflow
