Server:
  Jira: "https://my.jira.server.com"
  Confluence: "https://my.confluence.server.com"

Fields:
  Sprint: "customfield_10001"
  Story points: "customfield_10002"

Report: &Report
  Space: "SPACE"
  Parent page: "My Parent Page"

Workflow: &Workflow
  - Name: "Backlog"
    Status:
      - "Backlog"
  - Name: "In progress"
    Status:
      - "In progress"
      - "In review"
  - Name: "Done"
    Status:
      - "Closed"

Projects:
  - Name: "Project name"
    JQL: "project = TEST"
    Report: *Report
    Workflow: *Workflow
  - Name: "Second project name"
    JQL: "project = TEST2"
    Report: *Report
    Workflow: *Workflow
