server:
  jira: "https://my.jira.server.com"
  confluence: "https://my.confluence.server.com"

metrics:
  - status

fields:
  sprint: "customfield_10001"
  story_points: "customfield_10002"

projects:
  - name: "Project name"
    jql: "project = TEST"
    report:
      space: "SPACE"
      parent_page: "My Parent Page"
    workflow:
      - name: "Backlog"
        status:
          - "Backlog"
      - name: "In progress"
        status:
          - "In progress"
          - "In review"
      - name: "Done"
        status:
          - "Closed"
  - name: "Second project name"
    jql: "project = TEST2"
    report:
      space: "SPACE"
      parent_page: "My Parent Page"
    workflow:
      - name: "Backlog"
        status:
          - "Backlog"
      - name: "In progress"
        status:
          - "In progress"
          - "In review"
      - name: "Done"
        status:
          - "Closed"
